name: Book

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get mdbook
      run: wget https://github.com/rust-lang/mdBook/releases/download/v0.3.5/mdbook-v0.3.5-x86_64-unknown-linux-gnu.tar.gz -O - | tar xzf -
    - name: Build Book
      run: cd book && ../mdbook build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
          build_dir: book/book
