name: Rust

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: rustc version
      run: rustc --version
    - name: Cache
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('Cargo.toml') }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  book:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get mdbook
      run: wget https://github.com/rust-lang/mdBook/releases/download/v0.3.5/mdbook-v0.3.5-x86_64-unknown-linux-gnu.tar.gz -O - | tar xzf -
    - name: Build Book
      run: cd book && ../mdbook build
    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./book/book
